name: todolist_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  http: ^1.2.2           # To fetch data from external APIs
  shared_preferences: ^2.0.6 
  cupertino_icons: ^1.0.8 # To store data locally

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
